// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/services": {
    params: {};
  };
  "/services/performance-marketing": {
    params: {};
  };
  "/services/video-production": {
    params: {};
  };
  "/services/seo": {
    params: {};
  };
  "/services/social-media-marketing": {
    params: {};
  };
  "/services/influencer-marketing": {
    params: {};
  };
  "/services/web-development": {
    params: {};
  };
  "/services/360-digital-marketing": {
    params: {};
  };
  "/portfolio": {
    params: {};
  };
  "/studio": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/thank-you": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/admin": {
    params: {};
  };
  "/api/blogs": {
    params: {};
  };
  "/api/seo": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/services" | "/services/performance-marketing" | "/services/video-production" | "/services/seo" | "/services/social-media-marketing" | "/services/influencer-marketing" | "/services/web-development" | "/services/360-digital-marketing" | "/portfolio" | "/studio" | "/contact" | "/thank-you" | "/blog" | "/blog/:slug" | "/admin" | "/api/blogs" | "/api/seo";
  };
  "pages/Home/Home.tsx": {
    id: "pages/Home/Home";
    page: "/";
  };
  "pages/About/About.tsx": {
    id: "pages/About/About";
    page: "/about";
  };
  "pages/Services/Services.tsx": {
    id: "pages/Services/Services";
    page: "/services";
  };
  "pages/Services/PerformanceMarketing.tsx": {
    id: "pages/Services/PerformanceMarketing";
    page: "/services/performance-marketing";
  };
  "pages/Services/VideoProduction.tsx": {
    id: "pages/Services/VideoProduction";
    page: "/services/video-production";
  };
  "pages/Services/SEO.tsx": {
    id: "pages/Services/SEO";
    page: "/services/seo";
  };
  "pages/Services/SocialMediaMarketing.tsx": {
    id: "pages/Services/SocialMediaMarketing";
    page: "/services/social-media-marketing";
  };
  "pages/Services/InfluencerMarketing.tsx": {
    id: "pages/Services/InfluencerMarketing";
    page: "/services/influencer-marketing";
  };
  "pages/Services/WebDevelopment.tsx": {
    id: "pages/Services/WebDevelopment";
    page: "/services/web-development";
  };
  "pages/Services/Digital360.tsx": {
    id: "pages/Services/Digital360";
    page: "/services/360-digital-marketing";
  };
  "pages/Portfolio/Portfolio.tsx": {
    id: "pages/Portfolio/Portfolio";
    page: "/portfolio";
  };
  "pages/Studio/Studio.tsx": {
    id: "pages/Studio/Studio";
    page: "/studio";
  };
  "pages/Contact/Contact.tsx": {
    id: "pages/Contact/Contact";
    page: "/contact";
  };
  "pages/ThankYou/ThankYou.tsx": {
    id: "pages/ThankYou/ThankYou";
    page: "/thank-you";
  };
  "pages/Blog/Blog.tsx": {
    id: "pages/Blog/Blog";
    page: "/blog";
  };
  "pages/Blog/BlogPost.tsx": {
    id: "pages/Blog/BlogPost";
    page: "/blog/:slug";
  };
  "pages/Admin/Admin.tsx": {
    id: "pages/Admin/Admin";
    page: "/admin";
  };
  "pages/api/blogs.ts": {
    id: "pages/api/blogs";
    page: "/api/blogs";
  };
  "pages/api/seo.ts": {
    id: "pages/api/seo";
    page: "/api/seo";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "pages/Home/Home": typeof import("./src/pages/Home/Home.tsx");
  "pages/About/About": typeof import("./src/pages/About/About.tsx");
  "pages/Services/Services": typeof import("./src/pages/Services/Services.tsx");
  "pages/Services/PerformanceMarketing": typeof import("./src/pages/Services/PerformanceMarketing.tsx");
  "pages/Services/VideoProduction": typeof import("./src/pages/Services/VideoProduction.tsx");
  "pages/Services/SEO": typeof import("./src/pages/Services/SEO.tsx");
  "pages/Services/SocialMediaMarketing": typeof import("./src/pages/Services/SocialMediaMarketing.tsx");
  "pages/Services/InfluencerMarketing": typeof import("./src/pages/Services/InfluencerMarketing.tsx");
  "pages/Services/WebDevelopment": typeof import("./src/pages/Services/WebDevelopment.tsx");
  "pages/Services/Digital360": typeof import("./src/pages/Services/Digital360.tsx");
  "pages/Portfolio/Portfolio": typeof import("./src/pages/Portfolio/Portfolio.tsx");
  "pages/Studio/Studio": typeof import("./src/pages/Studio/Studio.tsx");
  "pages/Contact/Contact": typeof import("./src/pages/Contact/Contact.tsx");
  "pages/ThankYou/ThankYou": typeof import("./src/pages/ThankYou/ThankYou.tsx");
  "pages/Blog/Blog": typeof import("./src/pages/Blog/Blog.tsx");
  "pages/Blog/BlogPost": typeof import("./src/pages/Blog/BlogPost.tsx");
  "pages/Admin/Admin": typeof import("./src/pages/Admin/Admin.tsx");
  "pages/api/blogs": typeof import("./src/pages/api/blogs.ts");
  "pages/api/seo": typeof import("./src/pages/api/seo.ts");
};