import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("pages/Home/Home.tsx"),
  route("about-us", "pages/About/About.tsx"),
  route("life-at-cogent", "pages/LifeAtCogent/LifeAtCogent.tsx"),
  route("services", "pages/Services/Services.tsx"),
  route("ppc-company-in-jaipur", "pages/Services/PerformanceMarketing.tsx"),
  route("services/video-production", "pages/Services/VideoProduction.tsx"),
  route("best-seo-company-in-jaipur", "pages/Services/SEO.tsx"),
  route("best-social-media-marketing-company-in-jaipur", "pages/Services/SocialMediaMarketing.tsx"),
  route("services/influencer-marketing", "pages/Services/InfluencerMarketing.tsx"),
  route("website-development-company-in-jaipur", "pages/Services/WebDevelopment.tsx"),
  route("best-digital-marketing-company-in-jaipur", "pages/Services/Digital360.tsx"),
  route("portfolio", "pages/Portfolio/Portfolio.tsx"),
  route("studio", "pages/Studio/Studio.tsx"),
  route("contact", "pages/Contact/Contact.tsx"),
  route("thank-you", "pages/ThankYou/ThankYou.tsx"),
  route("d2c-marketing-agency-in-jaipur", "pages/Services/D2CMarketing.tsx"),
  route("content-marketing-agency-in-jaipur", "pages/Services/ContentMarketing.tsx"),
  route("marketing-consultant-in-jaipur", "pages/Services/MarketingConsultant.tsx"),
  route("blog", "pages/Blog/Blog.tsx"),
  route("blog/:slug", "pages/Blog/BlogPost.tsx"),
  route("admin", "pages/Admin/Admin.tsx"),
  route("api/blogs", "pages/api/blogs.ts"),
  route("api/seo", "pages/api/seo.ts"),
  route("api/enquiries", "pages/api/enquiries.ts"),
] as RouteConfig;
